#############################################################################
# Makefile for building: PPP_Assignment_2
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  PPP_Assignment_2.pro
# Template: app
# Command: /Users/albertolascala/Qt/5.8/clang_64/bin/qmake -o Makefile PPP_Assignment_2.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -msse -msse2 -msse3 -arch x86_64 -I/usr/local/include/SDL2 -D_THREAD_SAFE -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/Library/Frameworks/SDL.framework/Headers -isystem /usr/local/include/SDL2 -Iinclude -IGLFunctionsLib/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/albertolascala/Qt/5.8/clang_64/mkspecs/macx-clang
QMAKE         = /Users/albertolascala/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PPP_Assignment_21.0.0
DISTDIR = /Users/albertolascala/PPP_Assignment2/.tmp/PPP_Assignment_21.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS)
LIBS          = $(SUBLIBS) -F/Library/Frameworks -framework SDL2 -L /Users/albertolascala/PPP_Assignment2/GLFunctionsLib/lib -lGLFunctionsLib -L/usr/local/lib -lSDL2 -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/Window.cpp \
		src/GameObject.cpp \
		src/Player.cpp \
		src/UtilityFunctions.cpp \
		src/Mesh.cpp \
		src/Obstacle.cpp \
		src/Level.cpp \
		src/Bullet.cpp \
		src/Enemy.cpp \
		src/EnemySatellite.cpp \
		src/Particles.cpp \
		src/Particle.cpp 
OBJECTS       = main.o \
		Window.o \
		GameObject.o \
		Player.o \
		UtilityFunctions.o \
		Mesh.o \
		Obstacle.o \
		Level.o \
		Bullet.o \
		Enemy.o \
		EnemySatellite.o \
		Particles.o \
		Particle.o
DIST          = .qmake.stash \
		PPP_Assignment_2.pro include/Window.h \
		include/GameObject.h \
		include/Player.h \
		include/UtilityFunctions.h \
		include/Mesh.h \
		include/Obstacle.h \
		include/Level.h \
		include/Bullet.h \
		include/Enemy.h \
		include/EnemySatellite.h \
		include/Particles.h \
		include/Particle.h src/main.cpp \
		src/Window.cpp \
		src/GameObject.cpp \
		src/Player.cpp \
		src/UtilityFunctions.cpp \
		src/Mesh.cpp \
		src/Obstacle.cpp \
		src/Level.cpp \
		src/Bullet.cpp \
		src/Enemy.cpp \
		src/EnemySatellite.cpp \
		src/Particles.cpp \
		src/Particle.cpp
QMAKE_TARGET  = PPP_Assignment_2
DESTDIR       = 
TARGET        = PPP_Assignment_2


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PPP_Assignment_2.pro .qmake.cache /Users/albertolascala/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf /Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		PPP_Assignment_2.pro
	$(QMAKE) -o Makefile PPP_Assignment_2.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/qdevice.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/device_config.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/unix.conf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/mac.conf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/macx.conf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/clang.conf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/qconfig.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/default_post.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/yacc.prf:
/Users/albertolascala/Qt/5.8/clang_64/mkspecs/features/lex.prf:
PPP_Assignment_2.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile PPP_Assignment_2.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/main.cpp include/Window.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		include/Player.h \
		include/GameObject.h \
		include/UtilityFunctions.h \
		include/Mesh.h \
		include/Obstacle.h \
		include/Level.h \
		include/Bullet.h \
		include/Enemy.h \
		include/EnemySatellite.h \
		include/Particles.h \
		include/Particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Window.o: src/Window.cpp include/Window.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o src/Window.cpp

GameObject.o: src/GameObject.cpp include/GameObject.h \
		GLFunctionsLib/include/Vec4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameObject.o src/GameObject.cpp

Player.o: src/Player.cpp include/Player.h \
		include/GameObject.h \
		GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/GLFunctions.h \
		include/UtilityFunctions.h \
		include/Mesh.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o src/Player.cpp

UtilityFunctions.o: src/UtilityFunctions.cpp include/UtilityFunctions.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UtilityFunctions.o src/UtilityFunctions.cpp

Mesh.o: src/Mesh.cpp include/Mesh.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		include/UtilityFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mesh.o src/Mesh.cpp

Obstacle.o: src/Obstacle.cpp include/Obstacle.h \
		include/GameObject.h \
		GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/GLFunctions.h \
		include/UtilityFunctions.h \
		include/Mesh.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obstacle.o src/Obstacle.cpp

Level.o: src/Level.cpp include/Level.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		include/UtilityFunctions.h \
		include/Player.h \
		include/GameObject.h \
		include/Mesh.h \
		include/Obstacle.h \
		include/Bullet.h \
		include/Enemy.h \
		include/EnemySatellite.h \
		include/Particles.h \
		include/Particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Level.o src/Level.cpp

Bullet.o: src/Bullet.cpp include/Bullet.h \
		include/GameObject.h \
		GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/GLFunctions.h \
		include/UtilityFunctions.h \
		include/Mesh.h \
		include/Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bullet.o src/Bullet.cpp

Enemy.o: src/Enemy.cpp include/Enemy.h \
		include/GameObject.h \
		GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/GLFunctions.h \
		include/UtilityFunctions.h \
		include/Mesh.h \
		include/Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Enemy.o src/Enemy.cpp

EnemySatellite.o: src/EnemySatellite.cpp include/EnemySatellite.h \
		include/GameObject.h \
		GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/GLFunctions.h \
		include/UtilityFunctions.h \
		include/Mesh.h \
		include/Player.h \
		include/Enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemySatellite.o src/EnemySatellite.cpp

Particles.o: src/Particles.cpp include/Particles.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		include/Mesh.h \
		include/UtilityFunctions.h \
		include/Particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Particles.o src/Particles.cpp

Particle.o: src/Particle.cpp include/Particle.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		include/Mesh.h \
		include/UtilityFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Particle.o src/Particle.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

